on:
  push:

name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') # 只有这次 Commit 是 创建 Tag 时，才进行后续发布操作
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - run: go build -o dingdong_monitor_linux_x64
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o dingdong_monitor_windows_x64.exe
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o dingdong_monitor_windows_x86.exe
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o dingdong_monitor_darwin_x64
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o dingdong_monitor_darwin_arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dingdong_monitor_linux_x64
            dingdong_monitor_windows_x64.exe
            dingdong_monitor_windows_x86.exe
            dingdong_monitor_darwin_x64
            dingdong_monitor_darwin_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}